# config/sidekiq.yml

:schedule:
  hello_world:
    cron: '0 * * * * *'   # Runs once per minute
    class: HardJob
  auto_queue:
    cron: '0 * * * * *'   # Runs once per minute
    class: AutomateQueue
  doctor_clinic_notif:
    cron: '0 * * * * *'   # Runs once per minute
    class: DoctorClinicNotificationWorker
  appointments_today_notif:
    cron: '0 0 * * *'  
    class: AppointmentsTodayNotificationWorker
  build_clinic_queue:
    cron: '0 * * * * *'   # Runs once per minute
    class: BuildClinicQueueWorker
